# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PKNbXcWnuq8oWU3WNTklzFz9wV-XoENB
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from datetime import datetime

# Page config
st.set_page_config(
    page_title="CRM Support Analytics Dashboard",
    page_icon="🎯",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS
st.markdown("""
<style>
    .main { background-color: #080c14; }
    .stMetric {
        background-color: #0d1420;
        border: 1px solid rgba(0,212,255,0.15);
        border-radius: 10px;
        padding: 15px;
    }
    .stMetric label { color: #64748b !important; }
    .stMetric [data-testid="metric-container"] { color: white; }
    h1, h2, h3 { color: white !important; }
    .sidebar .sidebar-content { background-color: #0d1420; }
</style>
""", unsafe_allow_html=True)

# Load data
@st.cache_data
def load_data():
    df = pd.read_csv('crm_support_data.csv')
    df['created_at'] = pd.to_datetime(df['created_at'])
    df['resolved_at'] = pd.to_datetime(df['resolved_at'])
    return df

df = load_data()

# Sidebar filters
st.sidebar.title("🎛️ Filters")
st.sidebar.markdown("---")

selected_priority = st.sidebar.multiselect(
    "Priority",
    options=df['priority'].unique(),
    default=df['priority'].unique()
)

selected_status = st.sidebar.multiselect(
    "Status",
    options=df['status'].unique(),
    default=df['status'].unique()
)

selected_agent = st.sidebar.multiselect(
    "Agent",
    options=df['agent'].unique(),
    default=df['agent'].unique()
)

selected_group = st.sidebar.multiselect(
    "Support Group",
    options=df['group'].unique(),
    default=df['group'].unique()
)

# Filter data
filtered = df[
    (df['priority'].isin(selected_priority)) &
    (df['status'].isin(selected_status)) &
    (df['agent'].isin(selected_agent)) &
    (df['group'].isin(selected_group))
]

# Header
st.title("🎯 Customer Support Analytics Dashboard")
st.markdown("**Real-time CRM performance monitoring — built by Oluwatosin Ajisefinni**")
st.markdown("---")

# KPI Cards
total = len(filtered)
resolved = filtered[filtered['status'].isin(['Resolved', 'Closed'])]
open_tickets = filtered[filtered['status'].isin(['Open', 'Pending'])]
sla_breaches = filtered[filtered['sla_breached'] == True]
resolution_rate = (len(resolved) / total * 100) if total > 0 else 0
sla_compliance = ((total - len(sla_breaches)) / total * 100) if total > 0 else 0
avg_csat = filtered['csat_score'].mean()
avg_resolution = filtered['resolution_hours'].mean()

col1, col2, col3, col4, col5, col6 = st.columns(6)

with col1:
    st.metric("📋 Total Tickets", f"{total:,}")
with col2:
    st.metric("🟢 Open/Pending", f"{len(open_tickets):,}")
with col3:
    st.metric("✅ Resolution Rate", f"{resolution_rate:.1f}%")
with col4:
    st.metric("⏱️ Avg Resolution", f"{avg_resolution:.1f}h")
with col5:
    st.metric("📊 SLA Compliance", f"{sla_compliance:.1f}%")
with col6:
    st.metric("⭐ Avg CSAT", f"{avg_csat:.2f}/5.0")

st.markdown("---")

# Row 1 — Volume and Status
col1, col2 = st.columns([2, 1])

with col1:
    monthly = filtered.groupby('month').size().reset_index(name='count')
    fig1 = px.line(monthly, x='month', y='count',
                   title='📈 Monthly Ticket Volume Trend',
                   markers=True,
                   color_discrete_sequence=['#00d4ff'])
    fig1.update_layout(
        plot_bgcolor='#0d1420',
        paper_bgcolor='#0d1420',
        font_color='white',
        title_font_size=14
    )
    st.plotly_chart(fig1, use_container_width=True)

with col2:
    fig2 = px.pie(filtered, names='status',
                  title='🎯 Status Distribution',
                  color_discrete_sequence=px.colors.qualitative.Bold)
    fig2.update_layout(
        plot_bgcolor='#0d1420',
        paper_bgcolor='#0d1420',
        font_color='white',
        title_font_size=14
    )
    st.plotly_chart(fig2, use_container_width=True)

# Row 2 — Priority and Agent Performance
col1, col2 = st.columns(2)

with col1:
    priority_counts = filtered.groupby('priority').size().reset_index(name='count')
    fig3 = px.bar(priority_counts, x='priority', y='count',
                  title='🚨 Tickets by Priority',
                  color='priority',
                  color_discrete_map={
                      'Urgent': '#ff4444',
                      'High': '#ff8800',
                      'Medium': '#ffdd00',
                      'Low': '#00cc44'
                  })
    fig3.update_layout(
        plot_bgcolor='#0d1420',
        paper_bgcolor='#0d1420',
        font_color='white',
        title_font_size=14,
        showlegend=False
    )
    st.plotly_chart(fig3, use_container_width=True)

with col2:
    agent_stats = filtered.groupby('agent').agg(
        total=('ticket_id', 'count'),
        avg_csat=('csat_score', 'mean')
    ).reset_index().round(2)
    fig4 = px.bar(agent_stats, x='agent', y='total',
                  title='👤 Agent Ticket Volume',
                  color='avg_csat',
                  color_continuous_scale='RdYlGn',
                  text='total')
    fig4.update_layout(
        plot_bgcolor='#0d1420',
        paper_bgcolor='#0d1420',
        font_color='white',
        title_font_size=14
    )
    st.plotly_chart(fig4, use_container_width=True)

# Row 3 — SLA and Resolution
col1, col2 = st.columns(2)

with col1:
    sla_by_priority = filtered.groupby('priority').apply(
        lambda x: (x['sla_breached'] == False).sum() / len(x) * 100
    ).reset_index(name='compliance_rate').round(1)
    fig5 = px.bar(sla_by_priority, x='priority', y='compliance_rate',
                  title='✅ SLA Compliance by Priority (%)',
                  color='compliance_rate',
                  color_continuous_scale='RdYlGn',
                  text='compliance_rate')
    fig5.update_traces(texttemplate='%{text}%', textposition='outside')
    fig5.update_layout(
        plot_bgcolor='#0d1420',
        paper_bgcolor='#0d1420',
        font_color='white',
        title_font_size=14,
        yaxis_range=[0, 115]
    )
    st.plotly_chart(fig5, use_container_width=True)

with col2:
    res_time = filtered[filtered['resolution_hours'].notna()].groupby(
        'priority')['resolution_hours'].mean().reset_index()
    res_time.columns = ['priority', 'avg_hours']
    res_time = res_time.round(1)
    fig6 = px.bar(res_time, x='priority', y='avg_hours',
                  title='⏱️ Avg Resolution Time by Priority (Hours)',
                  color='priority',
                  color_discrete_map={
                      'Urgent': '#ff4444',
                      'High': '#ff8800',
                      'Medium': '#ffdd00',
                      'Low': '#00cc44'
                  },
                  text='avg_hours')
    fig6.update_traces(texttemplate='%{text}h', textposition='outside')
    fig6.update_layout(
        plot_bgcolor='#0d1420',
        paper_bgcolor='#0d1420',
        font_color='white',
        title_font_size=14,
        showlegend=False
    )
    st.plotly_chart(fig6, use_container_width=True)

# Row 4 — CSAT and Raw Data
col1, col2 = st.columns(2)

with col1:
    csat_data = filtered[filtered['csat_score'].notna()]
    fig7 = px.histogram(csat_data, x='csat_score',
                        title='⭐ CSAT Score Distribution',
                        nbins=5,
                        color_discrete_sequence=['#00d4ff'])
    fig7.update_layout(
        plot_bgcolor='#0d1420',
        paper_bgcolor='#0d1420',
        font_color='white',
        title_font_size=14
    )
    st.plotly_chart(fig7, use_container_width=True)

with col2:
    source_counts = filtered.groupby('source').size().reset_index(name='count')
    fig8 = px.pie(source_counts, names='source', values='count',
                  title='📞 Tickets by Source Channel',
                  color_discrete_sequence=px.colors.qualitative.Pastel)
    fig8.update_layout(
        plot_bgcolor='#0d1420',
        paper_bgcolor='#0d1420',
        font_color='white',
        title_font_size=14
    )
    st.plotly_chart(fig8, use_container_width=True)

# Raw data table
st.markdown("---")
st.subheader("📋 Ticket Data Explorer")
st.dataframe(
    filtered[['ticket_id', 'subject', 'type', 'status', 'priority',
              'agent', 'group', 'resolution_hours', 'sla_breached', 'csat_score']]
    .sort_values('ticket_id', ascending=False),
    use_container_width=True,
    height=300
)

st.markdown("---")
st.markdown("**Built by Oluwatosin Ajisefinni** | Data Analyst | Lagos, Nigeria | [GitHub](https://github.com/Thuqsin) | [LinkedIn](https://linkedin.com/in/oluwatosinajisefinni)")